/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114117-g4027c2e1d0-20240312"
#endif /* AVUTIL_FFVERSION_H */
